# Generated by Django 3.2.19 on 2025-07-29 16:46

import MotoSell.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa pliku')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Plik zdjęcia')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data dodania')),
            ],
            options={
                'verbose_name': 'Zdjęcie',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł ogłoszenia')),
                ('description', models.TextField(verbose_name='Opis')),
                ('category', models.CharField(choices=[('motocykl', 'Motocykl'), ('osobowe', 'Osobowy'), ('ciezarowy', 'Ciężarowy')], max_length=15, verbose_name='Kategoria')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Marka')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('make_year', models.IntegerField(validators=[MotoSell.models.validate_production_year], verbose_name='Rok produkcji')),
                ('mileage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Przebieg')),
                ('cubic_capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pojemność silnika')),
                ('power', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Moc (KM)')),
                ('fuel_type', models.CharField(choices=[('benzyna', 'Benzyna'), ('diesel', 'Diesel'), ('lpg', 'Benzyna+LPG')], max_length=20, verbose_name='Rodzaj paliwa')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('publication_date', models.DateTimeField(blank=True, null=True, verbose_name='Data publikacji')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_photo', to='MotoSell.image', verbose_name='Zdjęcie główne')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Pojazd',
                'verbose_name_plural': 'Pojazdy',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='MotoSell.image')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MotoSell.vehicle')),
            ],
            options={
                'verbose_name': 'Zdjęcie w galerii',
                'verbose_name_plural': 'Zdjęcia w galerii',
            },
        ),
        migrations.AddConstraint(
            model_name='gallery',
            constraint=models.UniqueConstraint(fields=('vehicle', 'image'), name='unique_image_per_vehicle_gallery'),
        ),
    ]
