# Generated by Django 3.2.19 on 2025-07-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Czy usunięto'),
        ),
    ]
