# Generated by Django 3.2.19 on 2025-07-30 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0002_vehicle_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='MotoSell.vehicle'),
        ),
    ]
