# Generated by Django 3.2.19 on 2025-07-30 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0003_alter_gallery_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_entries', to='MotoSell.image'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='MotoSell.vehicle'),
        ),
    ]
